import Head from 'next/head'
import React from 'react'

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>My page title</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <header>
          header
        </header>
        <main>
          {children}
        </main>
        <footer>
          footer
        </footer>
      </div>
    </>
  )
}

export default Layout